name: Playwright
on:
  push:
    branches: [main, production]

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  Integration:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.7.6
          run_install: true
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
